# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: bitnami/rabbitmq:3.8
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 15s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s
        env:
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest 
          RABBITMQ_MANAGEMENT_PORT_NUMBER: 15672
          RABBITMQ_VHOST: /
        ports:
          - 15672:15672
          - 5672:5672

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '8'

        
      - name: Before install
        shell: bash
        run: curl -i -k -v -u eiffel:eiffel123 -H "content-type:application/json" 
                   -XPUT -d'{"type":"topic","durable":true}'
                     http://${{ env.RABBITMQ_HOST }}:${{ env.RABBITMQ_MNG_PORT }}/api/exchanges/%2f/eiffel.test 
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_MNG_PORT: ${{ job.services.rabbitmq.ports[15672] }}
        

        
      - name: Run test
        run: mvn -V -B -U clean test jacoco:report
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
        
