# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:3.8-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 15672

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '8'

        
      - name: Before install
        run: curl -i -u guest:guest -H "content-type:application/json" -XPUT -d'{"type":"topic","durable":true}' -k https://0.0.0.0:15672/api/exchanges/%2f/eiffel.test 
        env:
          RABBITMQ_HOST: 0.0.0.0
          RABBITMQ_PORT: 15672

        
      - name: Run test
        run: mvn -V -B -U clean test jacoco:report
        
